server:
  port: 10010
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/1703a_p2p?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.40.128
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10088/eureka
  instance:
    prefer-ip-address: true # 当其它服务获取地址时提供ip而不是hostname
    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
zuul:
  prefix: /api # 添加路由前缀
  ignored-services: '*'   # 使用'*'可忽略所有微服务
  routes:
     p2p-user-service: /p2p_user_service/**
  sensitive-headers:
filter:
  whiteList:
  - /user/login
